import json
import re
import ast
from typing import Dict, Any
from engine.generator import LanguageGenerator, GeneratorError
from engine.workflow import Workflow
from utils.logger import get_logger
from config.config import Config

class PythonGenerator(LanguageGenerator):
    def __init__(self):
        super().__init__()
        self.logger = get_logger("python_generator")
        self.config = Config()
        self._indent_level = self.config.get("generator.indent_level", 4)
        self._expr_cache = {}

    def generate(self, workflow: Workflow) -> str:
        self.logger.info(f"Generating Python code for workflow: {workflow.function}")
        self._expr_cache.clear()
        try:
            code = [
                "# Generated by JSONFlow PythonGenerator",
                "import web3",
                "import solana",
                "import quantum_circuit",
                "context = {}",
                f"# Workflow: {workflow.function}",
                f"# Description: {workflow.metadata.get('description', 'N/A')}",
                f"# Schema Version: {workflow.metadata.get('schema_version', '1.1.0')}",
                f"async def {workflow.function}():"
            ]
            inputs = workflow.schema.get('inputs', {})
            for key, spec in inputs.items():
                if not isinstance(spec, dict) or 'type' not in spec:
                    self.logger.warning(f"Invalid input spec for {key}")
                    continue
                default = spec.get('default')
                constraints = spec.get('constraints', {})
                type_map = {
                    "string": "''",
                    "integer": "0",
                    "number": "0.0",
                    "boolean": "False",
                    "object": "{}",
                    "array": "[]",
                    "null": "None"
                }
                if default is None:
                    default = type_map.get(spec.get('type', 'null'), 'None')
                else:
                    if 'minLength' in constraints and isinstance(default, str) and len(default) < constraints['minLength']:
                        raise GeneratorError(f"Default value for {key} violates minLength")
                    if 'pattern' in constraints and isinstance(default, str) and not re.match(constraints['pattern'], default):
                        raise GeneratorError(f"Default value for {key} violates pattern")
                    if 'enum' in constraints and default not in constraints['enum']:
                        raise GeneratorError(f"Default value for {key} not in enum")
                    default = json.dumps(default)
                code.append(f"    context['{key}'] = {default}")
                if spec.get('ui'):
                    code.append(f"    # UI for {key}: {json.dumps(spec['ui'])}")
            for invariant in getattr(workflow, 'invariants', []):
                condition = self._safe_format_expr(invariant['condition'])
                message = invariant.get('message', 'Invariant failed')
                code.append(f"    if not ({condition}):")
                code.append(f"        raise ValueError(\"{message}\")")
            for step in workflow.steps:
                self.logger.debug(f"Generating code for step: {step.get('type')}")
                code.append(self.generate_step(step, indent=1))
            code.append("    return context")
            code.extend([
                "",
                "# Simulated helper functions",
                "async def simulate_ai_infer(model, input_data, params): return {'result': 'simulated'}",
                "async def simulate_workflow(id, args): return {'result': 'simulated'}",
                "async def simulate_crypto_sign(algorithm, data, key): return 'simulated_signature'",
                "async def simulate_crypto_verify(algorithm, data, signature, key): return True",
                "async def run_quantum_algorithm(algorithm, params): return {'result': 'simulated'}"
            ])
            return "\n".join(filter(None, code))
        except Exception as e:
            self.logger.error(f"Python code generation failed: {str(e)}")
            raise GeneratorError(f"Python code generation failed: {str(e)}")

    def generate_step(self, step: Dict[str, Any], indent: int) -> str:
        step_type = step.get('type')
        handlers = {
            'set': self.generate_set,
            'if': self.generate_if,
            'return': self.generate_return,
            'try': self.generate_try,
            'while': self.generate_while,
            'foreach': self.generate_foreach,
            'parallel': self.generate_parallel,
            'assert': self.generate_assert,
            'event': self.generate_event,
            'require_role': self.generate_require_role,
            'ai_infer': self.generate_ai_infer,
            'ai_train': self.generate_ai_train,
            'ai_classify': self.generate_ai_classify,
            'ai_embed': self.generate_ai_embed,
            'ai_explain': self.generate_ai_explain,
            'quantum_circuit': self.generate_quantum_circuit,
            'quantum_measure': self.generate_quantum_measure,
            'quantum_algorithm': self.generate_quantum_algorithm,
            'blockchain_operation': self.generate_blockchain_operation,
            'crypto_sign': self.generate_crypto_sign,
            'crypto_verify': self.generate_crypto_verify,
            'regex_match': self.generate_regex_match,
            'audit_log': self.generate_audit_log,
            'call_workflow': self.generate_call_workflow
        }
        handler = handlers.get(step_type)
        if handler:
            code = handler(step)
        elif step_type.startswith('custom_'):
            code = self.generate_custom(step)
        else:
            code = f"# Unsupported step type: {step_type}"
        if step.get('ui'):
            code = f"{code}\n    # UI: {json.dumps(step['ui'])}"
        return self._indent_code(code, indent)

    def generate_set(self, step: Dict[str, Any]) -> str:
        target = step.get('target')
        if not isinstance(target, str) or not target:
            raise GeneratorError("Invalid or missing target in set step")
        value = self._safe_format_expr(step['value'])
        return f"context['{target}'] = {value}"

    def generate_if(self, step: Dict[str, Any]) -> str:
        condition = self._safe_format_expr(step['condition'])
        then_code = "\n".join(self.generate_step(s, indent=2) for s in step['then'])
        else_code = "\n".join(self.generate_step(s, indent=2) for s in step.get('else', []))
        code = [f"if {condition}:"]
        code.append(then_code)
        if else_code:
            code.append("else:")
            code.append(else_code)
        return "\n".join(code)

    def generate_return(self, step: Dict[str, Any]) -> str:
        value = self._safe_format_expr(step['value'])
        return f"return {value}"

    def generate_try(self, step: Dict[str, Any]) -> str:
        body_code = "\n".join(self.generate_step(s, indent=2) for s in step['body'])
        catch = step.get('catch', {})
        catch_code = "\n".join(self.generate_step(s, indent=2) for s in catch.get('body', [])) if catch else ""
        finally_code = "\n".join(self.generate_step(s, indent=2) for s in step.get('finally', []))
        code = ["try:"]
        code.append(body_code)
        if catch_code:
            error_var = catch.get('error_var', 'error')
            if not re.match(r'^[a-zA-Z_][a-zA-Z0-9_]*$', error_var):
                raise GeneratorError(f"Invalid error variable name: {error_var}")
            code.append(f"except Exception as {error_var}:")
            code.append(f"    context['{error_var}'] = str({error_var})")
            code.append(catch_code)
        if finally_code:
            code.append("finally:")
            code.append(finally_code)
        return "\n".join(code)

    def generate_while(self, step: Dict[str, Any]) -> str:
        condition = self._safe_format_expr(step['condition'])
        body_code = "\n".join(self.generate_step(s, indent=2) for s in step['body'])
        return f"while {condition}:\n{body_code}"

    def generate_foreach(self, step: Dict[str, Any]) -> str:
        collection = self._safe_format_expr(step['collection'])
        iterator = step['iterator']
        if not re.match(r'^[a-zA-Z_][a-zA-Z0-9_]*$', iterator):
            raise GeneratorError(f"Invalid iterator name: {iterator}")
        body_code = "\n".join(self.generate_step(s, indent=2) for s in step['body'])
        return f"for {iterator} in {collection}:\n    context['{iterator}'] = {iterator}\n{body_code}"

    def generate_parallel(self, step: Dict[str, Any]) -> str:
        branches = step.get('branches', [])
        branch_codes = [
            "\n".join(self.generate_step(s, indent=2) for s in branch)
            for branch in branches
        ]
        tasks = ", ".join(f"(lambda: (\n{code}\n))()" for code in branch_codes)
        return f"import asyncio\nresults = await asyncio.gather({tasks})"

    def generate_assert(self, step: Dict[str, Any]) -> str:
        condition = self._safe_format_expr(step['condition'])
        message = step.get('message', 'Assertion failed')
        if not isinstance(message, str):
            raise GeneratorError("Assert message must be a string")
        return f"if not ({condition}):\n    raise AssertionError(\"{message}\")"

    def generate_event(self, step: Dict[str, Any]) -> str:
        name = step.get('name')
        params = step.get('params', {})
        params_str = ", ".join(f"{k}={self._safe_format_expr(v)}" for k, v in params.items())
        return f"print('Event: {name}', {{ {params_str} }})"

    def generate_require_role(self, step: Dict[str, Any]) -> str:
        role = step.get('role')
        return f"if '{role}' not in context.get('user_roles', []):\n    raise GeneratorError('Missing role: {role}')"

    def generate_ai_infer(self, step: Dict[str, Any]) -> str:
        model = step.get('model')
        input_data = self._safe_format_expr(step['input'])
        target = step.get('target')
        params = json.dumps(step.get('parameters', {}))
        if not model or not target:
            raise GeneratorError("Missing model or target in ai_infer step")
        return f"context['{target}'] = await simulate_ai_infer('{model}', {input_data}, {params})"

    def generate_ai_train(self, step: Dict[str, Any]) -> str:
        model = step.get('model')
        data = self._safe_format_expr(step['data'])
        target = step.get('target')
        params = json.dumps(step.get('parameters', {}))
        return f"context['{target}'] = await simulate_ai_train('{model}', {data}, {params})"

    def generate_ai_classify(self, step: Dict[str, Any]) -> str:
        model = step.get('model')
        input_data = self._safe_format_expr(step['input'])
        target = step.get('target')
        params = json.dumps(step.get('parameters', {}))
        return f"context['{target}'] = await simulate_ai_classify('{model}', {input_data}, {params})"

    def generate_ai_embed(self, step: Dict[str, Any]) -> str:
        model = step.get('model')
        input_data = self._safe_format_expr(step['input'])
        target = step.get('target')
        params = json.dumps(step.get('parameters', {}))
        return f"context['{target}'] = await simulate_ai_embed('{model}', {input_data}, {params})"

    def generate_ai_explain(self, step: Dict[str, Any]) -> str:
        model = step.get('model')
        input_data = self._safe_format_expr(step['input'])
        target = step.get('target')
        params = json.dumps(step.get('parameters', {}))
        return f"context['{target}'] = await simulate_ai_explain('{model}', {input_data}, {params})"

    def generate_quantum_circuit(self, step: Dict[str, Any]) -> str:
        gates = step.get('gates', [])
        qubits = step.get('qubits')
        target = step.get('target')
        if not gates or not qubits or not target:
            raise GeneratorError("Missing gates, qubits, or target in quantum_circuit step")
        gate_code = []
        for gate in gates:
            gate_type = gate.get('gate')
            target_qubit = gate.get('target')
            control = gate.get('control')
            params = gate.get('parameters', {})
            if gate_type in ['H', 'X', 'Y', 'Z', 'T', 'S']:
                gate_code.append(f"circuit.{gate_type.lower()}({target_qubit})")
            elif gate_type == 'CNOT':
                if control is None:
                    raise GeneratorError("Missing control qubit for CNOT gate")
                gate_code.append(f"circuit.cnot({control}, {target_qubit})")
            elif gate_type in ['RX', 'RY', 'RZ']:
                angle = params.get('angle')
                if angle is None:
                    raise GeneratorError(f"Missing angle for {gate_type} gate")
                gate_code.append(f"circuit.{gate_type.lower()}({target_qubit}, {angle})")
        return "\n".join([
            f"circuit = quantum_circuit.QuantumCircuit({qubits})",
            *gate_code,
            f"context['{target}'] = circuit"
        ])

    def generate_quantum_measure(self, step: Dict[str, Any]) -> str:
        circuit = self._safe_format_expr(step['circuit'])
        target = step.get('target')
        return f"context['{target}'] = await {circuit}.measure()"

    def generate_quantum_algorithm(self, step: Dict[str, Any]) -> str:
        algorithm = step.get('algorithm')
        params = json.dumps(step.get('parameters', {}))
        target = step.get('target')
        return f"context['{target}'] = await run_quantum_algorithm('{algorithm}', {params})"

    def generate_blockchain_operation(self, step: Dict[str, Any]) -> str:
        chain = step.get('chain')
        action = step.get('action')
        params = step.get('params', {})
        target = step.get('target')
        if chain == "ethereum" and action == "transfer":
            to_address = params.get('to')
            value = params.get('value')
            if not to_address or not re.match(r'^0x[a-fA-F0-9]{40}$', to_address):
                self.logger.warning(f"Invalid Ethereum address: {to_address}")
                return f"# Invalid Ethereum address: {to_address}"
            if not value or not isinstance(value, (int, str, float)):
                raise GeneratorError(f"Invalid value for transfer: {value}")
            sender = "context.get('sender', '0x0000000000000000000000000000000000000000')"
            return f"context['{target}'] = await web3.eth.send_transaction({{ 'from': {sender}, 'to': '{to_address}', 'value': {value} }})"
        elif chain == "solana" and action == "transfer":
            to_address = params.get('to')
            lamports = params.get('value')
            if not to_address or not re.match(r'^[1-9A-HJ-NP-Za-km-z]{32,44}$', to_address):
                raise GeneratorError(f"Invalid Solana address: {to_address}")
            return f"context['{target}'] = await solana.transfer('{to_address}', {lamports})"
        elif chain == "starknet" and action == "transfer":
            return f"context['{target}'] = await starknet.transfer({json.dumps(params)})"
        return f"# Unsupported blockchain operation: {chain} {action}"

    def generate_crypto_sign(self, step: Dict[str, Any]) -> str:
        algorithm = step.get('algorithm')
        data = self._safe_format_expr(step['data'])
        key = self._safe_format_expr(step['key'])
        target = step.get('target')
        return f"context['{target}'] = await simulate_crypto_sign('{algorithm}', {data}, {key})"

    def generate_crypto_verify(self, step: Dict[str, Any]) -> str:
        algorithm = step.get('algorithm')
        data = self._safe_format_expr(step['data'])
        signature = self._safe_format_expr(step['signature'])
        key = self._safe_format_expr(step['key'])
        target = step.get('target')
        return f"context['{target}'] = await simulate_crypto_verify('{algorithm}', {data}, {signature}, {key})"

    def generate_regex_match(self, step: Dict[str, Any]) -> str:
        pattern = step.get('pattern')
        input_data = self._safe_format_expr(step['input'])
        target = step.get('target')
        try:
            re.compile(pattern)
        except re.error:
            raise GeneratorError(f"Invalid regex pattern: {pattern}")
        return f"context['{target}'] = bool(re.match(r'{pattern}', str({input_data})))"

    def generate_audit_log(self, step: Dict[str, Any]) -> str:
        message = step.get('message')
        metadata = json.dumps(step.get('metadata', {}))
        return f"print('Audit: {message}', {metadata})"

    def generate_call_workflow(self, step: Dict[str, Any]) -> str:
        workflow_id = step.get('workflow')
        target = step.get('target')
        args = ", ".join(f"{k}={self._safe_format_expr(v)}" for k, v in step.get('args', {}).items())
        return f"context['{target}'] = await simulate_workflow('{workflow_id}', {{ {args} }})"

    def generate_custom(self, step: Dict[str, Any]) -> str:
        custom_type = step.get('type')
        props = step.get('custom_properties', {})
        return f"# Custom step: {custom_type} with properties {json.dumps(props)}"

    def _safe_format_expr(self, expr: Any) -> str:
        expr_key = json.dumps(expr)
        if expr_key in self._expr_cache:
            return self._expr_cache[expr_key]
        formatted = self._format_expr(expr)
        formatted = re.sub(r"context\.get\(['\"](.*?)['\"]\)", r"context.get('\1', None)", formatted)
        self._expr_cache[expr_key] = formatted
        return formatted

    def _format_expr(self, expr: Any) -> str:
        if not isinstance(expr, dict):
            return json.dumps(expr).replace('"', "'")
        if 'get' in expr:
            return f"context.get('{expr['get']}')"
        if 'value' in expr:
            return json.dumps(expr['value']).replace('"', "'")
        if 'add' in expr:
            return f"({' + '.join(self._format_expr(e) for e in expr['add'])})"
        if 'subtract' in expr:
            return f"({' - '.join(self._format_expr(e) for e in expr['subtract'])})"
        if 'multiply' in expr:
            return f"({' * '.join(self._format_expr(e) for e in expr['multiply'])})"
        if 'divide' in expr:
            return f"({' / '.join(self._format_expr(e) for e in expr['divide'])})"
        if 'compare' in expr:
            op_map = {'===': '==', '!==': '!='}
            op = op_map.get(expr['compare']['op'], expr['compare']['op'])
            return f"({self._format_expr(expr['compare']['left'])} {op} {self._format_expr(expr['compare']['right'])})"
        if 'not' in expr:
            return f"not ({self._format_expr(expr['not'])})"
        if 'and' in expr:
            return f"({' and '.join(self._format_expr(e) for e in expr['and'])})"
        if 'or' in expr:
            return f"({' or '.join(self._format_expr(e) for e in expr['or'])})"
        if 'concat' in expr:
            return f"(''.join(str({self._format_expr(e)}) for e in [{', '.join(self._format_expr(e) for e in expr['concat'])}]))"
        if 'hash' in expr:
            return f"hashlib.{expr['hash']['algorithm']}({self._format_expr(expr['hash']['input'])}).hexdigest()"
        if 'regex' in expr:
            return f"bool(re.match(r'{expr['regex']['pattern']}', str({self._format_expr(expr['regex']['input'])})))"
        raise GeneratorError(f"Unsupported expression: {expr}")

    def _indent_code(self, code: str, indent: int) -> str:
        indent_str = " " * (indent * self._indent_level)
        return "\n".join(indent_str + line for line in code.split("\n") if line.strip())

def register_python_generator():
    from engine.generator import register_generator
    register_generator('python', PythonGenerator)